// Seed laporan diekstrak verbatim dari sumber asli (data demo MBGWatch Mojokerto)
export const SEED_REPORTS = [
  {
    id: "MJK-PKL-2026-001",
    tanggal: "2026-06-04",
    waktu: "07:15",
    sekolah: "SDN Kauman",
    wilayah: "Kec. Prajurit Kulon",
    jenis: "Kualitas Makanan",
    deskripsi:
      "Nasi yang dibagikan terlihat kurang segar dan berbau tidak sedap saat tiba di sekolah.",
    status: "done",
    fotoLaporan: ["__demo_MJK-PKL-2026-001"],
    fotoVerif: ["__demo_v_MJK-PKL-2026-001"],
    hash: "aaaa2aaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED0",
    kredibilitas: 60,
    sppg: "SPPG Kota Mojokerto Prajuritkulon Kauman",
  },
  {
    id: "MJK-PKL-2026-002",
    tanggal: "2026-06-03",
    waktu: "08:30",
    sekolah: "SDN Kauman 2",
    wilayah: "Kec. Prajurit Kulon",
    jenis: "Keterlambatan Distribusi",
    deskripsi:
      "Pengiriman makanan terlambat lebih dari satu jam sehingga siswa menunggu cukup lama di kelas.",
    status: "verified",
    fotoLaporan: ["__demo_MJK-PKL-2026-002"],
    fotoVerif: ["__demo_v_MJK-PKL-2026-002"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED1",
    kredibilitas: 67,
    sppg: "SPPG Kota Mojokerto Prajuritkulon Kauman",
  },
  {
    id: "MJK-PKL-2026-003",
    tanggal: "2026-06-02",
    waktu: "09:45",
    sekolah: "MI Kauman 3",
    wilayah: "Kec. Prajurit Kulon",
    jenis: "Porsi Tidak Memadai",
    deskripsi:
      "Porsi makanan yang diterima siswa dinilai terlalu sedikit dibanding standar gizi yang ditetapkan.",
    status: "pending",
    fotoLaporan: ["__demo_MJK-PKL-2026-003"],
    fotoVerif: [],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: null,
    deviceId: "DEVSEED2",
    kredibilitas: 74,
    sppg: "SPPG Kota Mojokerto Prajuritkulon Kauman",
  },
  {
    id: "MJK-PKL-2026-004",
    tanggal: "2026-06-01",
    waktu: "11:20",
    sekolah: "SMPN Mentikan",
    wilayah: "Kec. Prajurit Kulon",
    jenis: "Dugaan Penyimpangan",
    deskripsi:
      "Terdapat dugaan ketidaksesuaian jumlah penerima manfaat dengan laporan distribusi harian di lokasi ini.",
    status: "done",
    fotoLaporan: ["__demo_MJK-PKL-2026-004"],
    fotoVerif: ["__demo_v_MJK-PKL-2026-004"],
    hash: "aa2aaaaaaaa2aaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED3",
    kredibilitas: 81,
    sppg: "SPPG Kota Mojokerto Prajuritkulon Mentikan",
  },
  {
    id: "MJK-PKL-2026-005",
    tanggal: "2026-05-31",
    waktu: "12:05",
    sekolah: "TK Prajuritkulon",
    wilayah: "Kec. Prajurit Kulon",
    jenis: "Kebersihan / Sanitasi",
    deskripsi:
      "Kondisi wadah dan area distribusi makanan kurang bersih sehingga perlu perhatian dan penanganan segera.",
    status: "verified",
    fotoLaporan: ["__demo_MJK-PKL-2026-005"],
    fotoVerif: ["__demo_v_MJK-PKL-2026-005"],
    hash: "aaaa2aaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED4",
    kredibilitas: 88,
    sppg: "SPPG Kota Mojokerto Prajuritkulon Prajuritkulon",
  },
  {
    id: "MJK-PKL-2026-006",
    tanggal: "2026-05-30",
    waktu: "13:40",
    sekolah: "MTs Pulorejo",
    wilayah: "Kec. Prajurit Kulon",
    jenis: "Lainnya",
    deskripsi:
      "Terdapat catatan tambahan terkait pelaksanaan program makan bergizi gratis di lokasi sekolah ini.",
    status: "done",
    fotoLaporan: ["__demo_MJK-PKL-2026-006"],
    fotoVerif: ["__demo_v_MJK-PKL-2026-006"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED5",
    kredibilitas: 95,
    sppg: "SPPG Kota Mojokerto Prajuritkulon Pulorejo",
  },
  {
    id: "MJK-PKL-2026-007",
    tanggal: "2026-05-29",
    waktu: "07:15",
    sekolah: "SDN Pulorejo 2",
    wilayah: "Kec. Prajurit Kulon",
    jenis: "Kualitas Makanan",
    deskripsi:
      "Nasi yang dibagikan terlihat kurang segar dan berbau tidak sedap saat tiba di sekolah.",
    status: "done",
    fotoLaporan: ["__demo_MJK-PKL-2026-007"],
    fotoVerif: ["__demo_v_MJK-PKL-2026-007"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED0",
    kredibilitas: 66,
    sppg: "SPPG Kota Mojokerto Prajuritkulon Pulorejo",
  },
  {
    id: "MJK-PKL-2026-008",
    tanggal: "2026-05-28",
    waktu: "08:30",
    sekolah: "SDN Pulorejo 3",
    wilayah: "Kec. Prajurit Kulon",
    jenis: "Keterlambatan Distribusi",
    deskripsi:
      "Pengiriman makanan terlambat lebih dari satu jam sehingga siswa menunggu cukup lama di kelas.",
    status: "verified",
    fotoLaporan: ["__demo_MJK-PKL-2026-008"],
    fotoVerif: ["__demo_v_MJK-PKL-2026-008"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED1",
    kredibilitas: 73,
    sppg: "SPPG Kota Mojokerto Prajuritkulon Pulorejo",
  },
  {
    id: "MJK-PKL-2026-009",
    tanggal: "2026-05-27",
    waktu: "09:45",
    sekolah: "MI Pulorejo 4",
    wilayah: "Kec. Prajurit Kulon",
    jenis: "Porsi Tidak Memadai",
    deskripsi:
      "Porsi makanan yang diterima siswa dinilai terlalu sedikit dibanding standar gizi yang ditetapkan.",
    status: "pending",
    fotoLaporan: ["__demo_MJK-PKL-2026-009"],
    fotoVerif: [],
    hash: "aaa2aaaaaaaaaaaa",
    verified_by: null,
    deviceId: "DEVSEED2",
    kredibilitas: 80,
    sppg: "SPPG Kota Mojokerto Prajuritkulon Pulorejo",
  },
  {
    id: "MJK-PKL-2026-010",
    tanggal: "2026-05-26",
    waktu: "11:20",
    sekolah: "SMPN Pulorejo",
    wilayah: "Kec. Prajurit Kulon",
    jenis: "Dugaan Penyimpangan",
    deskripsi:
      "Terdapat dugaan ketidaksesuaian jumlah penerima manfaat dengan laporan distribusi harian di lokasi ini.",
    status: "done",
    fotoLaporan: ["__demo_MJK-PKL-2026-010"],
    fotoVerif: ["__demo_v_MJK-PKL-2026-010"],
    hash: "aaaaaaaaa2aaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED3",
    kredibilitas: 87,
    sppg: "SPPG Kota Mojokerto Prajuritkulon Pulorejo 2",
  },
  {
    id: "MJK-PKL-2026-011",
    tanggal: "2026-05-25",
    waktu: "12:05",
    sekolah: "TK Pulorejo 2",
    wilayah: "Kec. Prajurit Kulon",
    jenis: "Kebersihan / Sanitasi",
    deskripsi:
      "Kondisi wadah dan area distribusi makanan kurang bersih sehingga perlu perhatian dan penanganan segera.",
    status: "verified",
    fotoLaporan: ["__demo_MJK-PKL-2026-011"],
    fotoVerif: ["__demo_v_MJK-PKL-2026-011"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED4",
    kredibilitas: 94,
    sppg: "SPPG Kota Mojokerto Prajuritkulon Pulorejo 2",
  },
  {
    id: "MJK-PKL-2026-012",
    tanggal: "2026-05-24",
    waktu: "13:40",
    sekolah: "MTs Blooto",
    wilayah: "Kec. Prajurit Kulon",
    jenis: "Lainnya",
    deskripsi:
      "Terdapat catatan tambahan terkait pelaksanaan program makan bergizi gratis di lokasi sekolah ini.",
    status: "done",
    fotoLaporan: ["__demo_MJK-PKL-2026-012"],
    fotoVerif: ["__demo_v_MJK-PKL-2026-012"],
    hash: "aaa2aaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED5",
    kredibilitas: 65,
    sppg: "SPPG Kota Mojokerto Prajuritkulon Blooto",
  },
  {
    id: "MJK-PKL-2026-013",
    tanggal: "2026-05-23",
    waktu: "07:15",
    sekolah: "SDN Blooto 2",
    wilayah: "Kec. Prajurit Kulon",
    jenis: "Kualitas Makanan",
    deskripsi:
      "Nasi yang dibagikan terlihat kurang segar dan berbau tidak sedap saat tiba di sekolah.",
    status: "done",
    fotoLaporan: ["__demo_MJK-PKL-2026-013"],
    fotoVerif: ["__demo_v_MJK-PKL-2026-013"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED0",
    kredibilitas: 72,
    sppg: "SPPG Kota Mojokerto Prajuritkulon Blooto",
  },
  {
    id: "MJK-PKL-2026-014",
    tanggal: "2026-05-22",
    waktu: "08:30",
    sekolah: "SDN Blooto 3",
    wilayah: "Kec. Prajurit Kulon",
    jenis: "Keterlambatan Distribusi",
    deskripsi:
      "Pengiriman makanan terlambat lebih dari satu jam sehingga siswa menunggu cukup lama di kelas.",
    status: "verified",
    fotoLaporan: ["__demo_MJK-PKL-2026-014"],
    fotoVerif: ["__demo_v_MJK-PKL-2026-014"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED1",
    kredibilitas: 79,
    sppg: "SPPG Kota Mojokerto Prajuritkulon Blooto",
  },
  {
    id: "MJK-MGR-2026-001",
    tanggal: "2026-05-21",
    waktu: "09:45",
    sekolah: "MI Magersari",
    wilayah: "Kec. Magersari",
    jenis: "Porsi Tidak Memadai",
    deskripsi:
      "Porsi makanan yang diterima siswa dinilai terlalu sedikit dibanding standar gizi yang ditetapkan.",
    status: "pending",
    fotoLaporan: ["__demo_MJK-MGR-2026-001"],
    fotoVerif: [],
    hash: "aaaaaa2aaaaaaaaa",
    verified_by: null,
    deviceId: "DEVSEED2",
    kredibilitas: 86,
    sppg: "SPPG Kota Mojokerto Magersari Magersari 2",
  },
  {
    id: "MJK-MGR-2026-002",
    tanggal: "2026-05-20",
    waktu: "11:20",
    sekolah: "SMPN Magersari 2",
    wilayah: "Kec. Magersari",
    jenis: "Dugaan Penyimpangan",
    deskripsi:
      "Terdapat dugaan ketidaksesuaian jumlah penerima manfaat dengan laporan distribusi harian di lokasi ini.",
    status: "done",
    fotoLaporan: ["__demo_MJK-MGR-2026-002"],
    fotoVerif: ["__demo_v_MJK-MGR-2026-002"],
    hash: "aa2aaaaaaaaaaa2a",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED3",
    kredibilitas: 93,
    sppg: "SPPG Kota Mojokerto Magersari Magersari 2",
  },
  {
    id: "MJK-MGR-2026-003",
    tanggal: "2026-05-19",
    waktu: "12:05",
    sekolah: "TK Magersari",
    wilayah: "Kec. Magersari",
    jenis: "Kebersihan / Sanitasi",
    deskripsi:
      "Kondisi wadah dan area distribusi makanan kurang bersih sehingga perlu perhatian dan penanganan segera.",
    status: "verified",
    fotoLaporan: ["__demo_MJK-MGR-2026-003"],
    fotoVerif: ["__demo_v_MJK-MGR-2026-003"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED4",
    kredibilitas: 64,
    sppg: "SPPG Kota Mojokerto Magersari Magersari",
  },
  {
    id: "MJK-MGR-2026-004",
    tanggal: "2026-05-18",
    waktu: "13:40",
    sekolah: "MTs Magersari 2",
    wilayah: "Kec. Magersari",
    jenis: "Lainnya",
    deskripsi:
      "Terdapat catatan tambahan terkait pelaksanaan program makan bergizi gratis di lokasi sekolah ini.",
    status: "done",
    fotoLaporan: ["__demo_MJK-MGR-2026-004"],
    fotoVerif: ["__demo_v_MJK-MGR-2026-004"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED5",
    kredibilitas: 71,
    sppg: "SPPG Kota Mojokerto Magersari Magersari",
  },
  {
    id: "MJK-MGR-2026-005",
    tanggal: "2026-05-17",
    waktu: "07:15",
    sekolah: "SDN Magersari 3",
    wilayah: "Kec. Magersari",
    jenis: "Kualitas Makanan",
    deskripsi:
      "Nasi yang dibagikan terlihat kurang segar dan berbau tidak sedap saat tiba di sekolah.",
    status: "done",
    fotoLaporan: ["__demo_MJK-MGR-2026-005"],
    fotoVerif: ["__demo_v_MJK-MGR-2026-005"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED0",
    kredibilitas: 78,
    sppg: "SPPG Kota Mojokerto Magersari Magersari",
  },
  {
    id: "MJK-MGR-2026-006",
    tanggal: "2026-05-16",
    waktu: "08:30",
    sekolah: "SDN Wates",
    wilayah: "Kec. Magersari",
    jenis: "Keterlambatan Distribusi",
    deskripsi:
      "Pengiriman makanan terlambat lebih dari satu jam sehingga siswa menunggu cukup lama di kelas.",
    status: "verified",
    fotoLaporan: ["__demo_MJK-MGR-2026-006"],
    fotoVerif: ["__demo_v_MJK-MGR-2026-006"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED1",
    kredibilitas: 85,
    sppg: "SPPG Kota Mojokerto Magersari Wates",
  },
  {
    id: "MJK-MGR-2026-007",
    tanggal: "2026-05-15",
    waktu: "09:45",
    sekolah: "MI Kedundung",
    wilayah: "Kec. Magersari",
    jenis: "Porsi Tidak Memadai",
    deskripsi:
      "Porsi makanan yang diterima siswa dinilai terlalu sedikit dibanding standar gizi yang ditetapkan.",
    status: "pending",
    fotoLaporan: ["__demo_MJK-MGR-2026-007"],
    fotoVerif: [],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: null,
    deviceId: "DEVSEED2",
    kredibilitas: 92,
    sppg: "SPPG Kota Mojokerto Magersari Kedundung",
  },
  {
    id: "MJK-MGR-2026-008",
    tanggal: "2026-05-14",
    waktu: "11:20",
    sekolah: "SMPN Kedundung 2",
    wilayah: "Kec. Magersari",
    jenis: "Dugaan Penyimpangan",
    deskripsi:
      "Terdapat dugaan ketidaksesuaian jumlah penerima manfaat dengan laporan distribusi harian di lokasi ini.",
    status: "done",
    fotoLaporan: ["__demo_MJK-MGR-2026-008"],
    fotoVerif: ["__demo_v_MJK-MGR-2026-008"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED3",
    kredibilitas: 63,
    sppg: "SPPG Kota Mojokerto Magersari Kedundung",
  },
  {
    id: "MJK-MGR-2026-009",
    tanggal: "2026-05-13",
    waktu: "12:05",
    sekolah: "TK Kedundung 3",
    wilayah: "Kec. Magersari",
    jenis: "Kebersihan / Sanitasi",
    deskripsi:
      "Kondisi wadah dan area distribusi makanan kurang bersih sehingga perlu perhatian dan penanganan segera.",
    status: "verified",
    fotoLaporan: ["__demo_MJK-MGR-2026-009"],
    fotoVerif: ["__demo_v_MJK-MGR-2026-009"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED4",
    kredibilitas: 70,
    sppg: "SPPG Kota Mojokerto Magersari Kedundung",
  },
  {
    id: "MJK-MGR-2026-010",
    tanggal: "2026-05-12",
    waktu: "13:40",
    sekolah: "MTs Kedundung 4",
    wilayah: "Kec. Magersari",
    jenis: "Lainnya",
    deskripsi:
      "Terdapat catatan tambahan terkait pelaksanaan program makan bergizi gratis di lokasi sekolah ini.",
    status: "done",
    fotoLaporan: ["__demo_MJK-MGR-2026-010"],
    fotoVerif: ["__demo_v_MJK-MGR-2026-010"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED5",
    kredibilitas: 77,
    sppg: "SPPG Kota Mojokerto Magersari Kedundung",
  },
  {
    id: "MJK-MGR-2026-011",
    tanggal: "2026-05-11",
    waktu: "07:15",
    sekolah: "SDN Kedundung",
    wilayah: "Kec. Magersari",
    jenis: "Dugaan Penyimpangan",
    deskripsi:
      "Terdapat dugaan ketidaksesuaian jumlah penerima manfaat dengan laporan distribusi harian di lokasi ini.",
    status: "pending",
    fotoLaporan: ["__demo_MJK-MGR-2026-011"],
    fotoVerif: [],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: null,
    deviceId: "DEVSEED0",
    kredibilitas: 84,
    sppg: "SPPG Kota Mojokerto Magersari Kedundung 2",
  },
  {
    id: "MJK-MGR-2026-012",
    tanggal: "2026-05-10",
    waktu: "08:30",
    sekolah: "SDN Kedundung 2",
    wilayah: "Kec. Magersari",
    jenis: "Kualitas Makanan",
    deskripsi:
      "Nasi yang dibagikan terlihat kurang segar dan berbau tidak sedap saat tiba di sekolah.",
    status: "pending",
    fotoLaporan: ["__demo_MJK-MGR-2026-012"],
    fotoVerif: [],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: null,
    deviceId: "DEVSEED1",
    kredibilitas: 91,
    sppg: "SPPG Kota Mojokerto Magersari Kedundung 2",
  },
  {
    id: "MJK-MGR-2026-013",
    tanggal: "2026-05-09",
    waktu: "09:45",
    sekolah: "MI Kedundung 3",
    wilayah: "Kec. Magersari",
    jenis: "Porsi Tidak Memadai",
    deskripsi:
      "Porsi makanan yang diterima siswa dinilai terlalu sedikit dibanding standar gizi yang ditetapkan.",
    status: "verified",
    fotoLaporan: ["__demo_MJK-MGR-2026-013"],
    fotoVerif: ["__demo_v_MJK-MGR-2026-013"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED2",
    kredibilitas: 62,
    sppg: "SPPG Kota Mojokerto Magersari Kedundung 2",
  },
  {
    id: "MJK-MGR-2026-014",
    tanggal: "2026-05-08",
    waktu: "11:20",
    sekolah: "SMPN Kedundung 4",
    wilayah: "Kec. Magersari",
    jenis: "Dugaan Penyimpangan",
    deskripsi:
      "Terdapat dugaan ketidaksesuaian jumlah penerima manfaat dengan laporan distribusi harian di lokasi ini.",
    status: "pending",
    fotoLaporan: ["__demo_MJK-MGR-2026-014"],
    fotoVerif: [],
    hash: "aaaaaaaaaaaa2aaa",
    verified_by: null,
    deviceId: "DEVSEED3",
    kredibilitas: 69,
    sppg: "SPPG Kota Mojokerto Magersari Kedundung 2",
  },
  {
    id: "MJK-MGR-2026-015",
    tanggal: "2026-06-04",
    waktu: "12:05",
    sekolah: "TK Kedundung 5",
    wilayah: "Kec. Magersari",
    jenis: "Kualitas Makanan",
    deskripsi:
      "Nasi yang dibagikan terlihat kurang segar dan berbau tidak sedap saat tiba di sekolah.",
    status: "done",
    fotoLaporan: ["__demo_MJK-MGR-2026-015"],
    fotoVerif: ["__demo_v_MJK-MGR-2026-015"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED4",
    kredibilitas: 76,
    sppg: "SPPG Kota Mojokerto Magersari Kedundung 2",
  },
  {
    id: "MJK-KRG-2026-001",
    tanggal: "2026-06-03",
    waktu: "13:40",
    sekolah: "MTs Miji",
    wilayah: "Kec. Kranggan",
    jenis: "Lainnya",
    deskripsi:
      "Terdapat catatan tambahan terkait pelaksanaan program makan bergizi gratis di lokasi sekolah ini.",
    status: "done",
    fotoLaporan: ["__demo_MJK-KRG-2026-001"],
    fotoVerif: ["__demo_v_MJK-KRG-2026-001"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED5",
    kredibilitas: 83,
    sppg: "SPPG Kota Mojokerto Kranggan Miji 2",
  },
  {
    id: "MJK-KRG-2026-002",
    tanggal: "2026-06-02",
    waktu: "07:15",
    sekolah: "SDN Meri",
    wilayah: "Kec. Kranggan",
    jenis: "Kualitas Makanan",
    deskripsi:
      "Nasi yang dibagikan terlihat kurang segar dan berbau tidak sedap saat tiba di sekolah.",
    status: "done",
    fotoLaporan: ["__demo_MJK-KRG-2026-002"],
    fotoVerif: ["__demo_v_MJK-KRG-2026-002"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED0",
    kredibilitas: 90,
    sppg: "SPPG Kota Mojokerto Kranggan Meri",
  },
  {
    id: "MJK-KRG-2026-003",
    tanggal: "2026-06-01",
    waktu: "08:30",
    sekolah: "SDN Meri 2",
    wilayah: "Kec. Kranggan",
    jenis: "Keterlambatan Distribusi",
    deskripsi:
      "Pengiriman makanan terlambat lebih dari satu jam sehingga siswa menunggu cukup lama di kelas.",
    status: "verified",
    fotoLaporan: ["__demo_MJK-KRG-2026-003"],
    fotoVerif: ["__demo_v_MJK-KRG-2026-003"],
    hash: "aaaaaaaaaaaaaaaa",
    verified_by: "Pemkot Mojokerto",
    deviceId: "DEVSEED1",
    kredibilitas: 61,
    sppg: "SPPG Kota Mojokerto Kranggan Meri",
  },
  {
    id: "MJK-KRG-2026-004",
    tanggal: "2026-05-31",
    waktu: "09:45",
    sekolah: "MI Purwotengah",
    wilayah: "Kec. Kranggan",
    jenis: "Porsi Tidak Memadai",
    deskripsi:
      "Porsi makanan yang diterima siswa dinilai terlalu sedikit dibanding standar gizi yang ditetapkan.",
    status: "pending",
    fotoLaporan: ["__demo_MJK-KRG-2026-004"],
    fotoVerif: [],
    hash: "aaaaaaaaaaaa2aaa",
    verified_by: null,
    deviceId: "DEVSEED2",
    kredibilitas: 68,
    sppg: "SPPG Kota Mojokerto Kranggan Purwotengah",
  },
];
