// Daftar 18 SPPG Kota Mojokerto (3 kecamatan).
// Direproduksi 1:1 dari array `w` pada sumber asli (urutan & nilai dipertahankan).
export const SPPG_LIST = [
  {
    no: 22,
    kecamatan: "Prajurit Kulon",
    kelurahan: "Kauman",
    alamat: "Jl. Kyai H. Hasyim Ashari No.01, Kauman",
    nama: "SPPG Kota Mojokerto Prajuritkulon Kauman",
    skor: 87,
    laporan: 3,
    status: "Aktif",
    slhs: "punya",
  },
  {
    no: 50,
    kecamatan: "Prajurit Kulon",
    kelurahan: "Mentikan",
    alamat: "Cakarayam Gang 1 No 1-9, Mentikan",
    nama: "SPPG Kota Mojokerto Prajuritkulon Mentikan",
    skor: 83,
    laporan: 1,
    status: "Aktif",
    slhs: "proses",
  },
  {
    no: 63,
    kecamatan: "Prajurit Kulon",
    kelurahan: "Prajuritkulon",
    alamat: "Desa Prajuritkulon, Kec. Prajuritkulon",
    nama: "SPPG Kota Mojokerto Prajuritkulon Prajuritkulon 2",
    skor: 95,
    laporan: 0,
    status: "Aktif",
    slhs: "punya",
  },
  {
    no: 83,
    kecamatan: "Prajurit Kulon",
    kelurahan: "Prajuritkulon",
    alamat: "Prajurit Kulon, Kec. Prajuritkulon",
    nama: "SPPG Kota Mojokerto Prajuritkulon Prajuritkulon",
    skor: 90,
    laporan: 1,
    status: "Aktif",
    slhs: "punya",
  },
  {
    no: 90,
    kecamatan: "Prajurit Kulon",
    kelurahan: "Pulorejo",
    alamat: "Jl. Pendidikan Lingk. Rt.002/001, Pulorejo",
    nama: "SPPG Kota Mojokerto Prajuritkulon Pulorejo",
    skor: 72,
    laporan: 4,
    status: "Aktif",
    slhs: "tidak",
  },
  {
    no: 113,
    kecamatan: "Prajurit Kulon",
    kelurahan: "Pulorejo",
    alamat: "Jl. Cancer, Pulorejo, Kec. Prajuritkulon",
    nama: "SPPG Kota Mojokerto Prajuritkulon Pulorejo 2",
    skor: 85,
    laporan: 2,
    status: "Aktif",
    slhs: "proses",
  },
  {
    no: 115,
    kecamatan: "Prajurit Kulon",
    kelurahan: "Blooto",
    alamat: "Dusun Kemasan Gang 2 Rt02/03, Blooto",
    nama: "SPPG Kota Mojokerto Prajuritkulon Blooto",
    skor: 78,
    laporan: 3,
    status: "Aktif",
    slhs: "tidak",
  },
  {
    no: 8,
    kecamatan: "Magersari",
    kelurahan: "Magersari",
    alamat: "Jagalan, Kec. Magersari",
    nama: "SPPG Kota Mojokerto Magersari Magersari 2",
    skor: 88,
    laporan: 2,
    status: "Aktif",
    slhs: "punya",
  },
  {
    no: 11,
    kecamatan: "Magersari",
    kelurahan: "Magersari",
    alamat: "Jl. Raya Meri No.439, Meri, Kec. Magersari",
    nama: "SPPG Kota Mojokerto Magersari Magersari",
    skor: 82,
    laporan: 3,
    status: "Aktif",
    slhs: "punya",
  },
  {
    no: 44,
    kecamatan: "Magersari",
    kelurahan: "Wates",
    alamat: "Karanglo Gg. 1 No. 26 RT02/RW02, Wates",
    nama: "SPPG Kota Mojokerto Magersari Wates",
    skor: 91,
    laporan: 1,
    status: "Aktif",
    slhs: "punya",
  },
  {
    no: 53,
    kecamatan: "Magersari",
    kelurahan: "Kedundung",
    alamat: "Jalan Al-Azhar No. 1, Kedundung",
    nama: "SPPG Kota Mojokerto Magersari Kedundung",
    skor: 76,
    laporan: 4,
    status: "Aktif",
    slhs: "tidak",
  },
  {
    no: 91,
    kecamatan: "Magersari",
    kelurahan: "Kedundung",
    alamat: "Gg. Macan No.62 RT04/RW02, Kedundung",
    nama: "SPPG Kota Mojokerto Magersari Kedundung 2",
    skor: 69,
    laporan: 5,
    status: "Masalah",
    slhs: "tidak",
  },
  {
    no: 102,
    kecamatan: "Magersari",
    kelurahan: "Balongsari",
    alamat: "Desa Balongsari, Kec. Magersari",
    nama: "SPPG Kota Mojokerto Magersari Balongsari",
    skor: 94,
    laporan: 0,
    status: "Aktif",
    slhs: "punya",
  },
  {
    no: 15,
    kecamatan: "Kranggan",
    kelurahan: "Miji",
    alamat: "Kedungkwali Gg.1 No.48 Rt004/003, Miji",
    nama: "SPPG Kota Mojokerto Kranggan Miji 2",
    skor: 88,
    laporan: 1,
    status: "Aktif",
    slhs: "punya",
  },
  {
    no: 37,
    kecamatan: "Kranggan",
    kelurahan: "Meri",
    alamat: "Lingk. Kuwung Rt02/03, Meri, Kec. Kranggan",
    nama: "SPPG Kota Mojokerto Kranggan Meri 2",
    skor: 93,
    laporan: 0,
    status: "Aktif",
    slhs: "punya",
  },
  {
    no: 80,
    kecamatan: "Kranggan",
    kelurahan: "Miji",
    alamat: "Jl. Miji Gg. 1 No. 4, Kel. Miji, Kranggan",
    nama: "SPPG Kota Mojokerto Kranggan Miji",
    skor: 97,
    laporan: 0,
    status: "Aktif",
    slhs: "punya",
  },
  {
    no: 89,
    kecamatan: "Kranggan",
    kelurahan: "Meri",
    alamat: "Jalan Tropodo, Meri, Kec. Kranggan",
    nama: "SPPG Kota Mojokerto Kranggan Meri",
    skor: 84,
    laporan: 2,
    status: "Aktif",
    slhs: "proses",
  },
  {
    no: 122,
    kecamatan: "Kranggan",
    kelurahan: "Purwotengah",
    alamat: "Jl. Taman Siswa No. 14, Purwotengah",
    nama: "SPPG Kota Mojokerto Kranggan Purwotengah",
    skor: 91,
    laporan: 1,
    status: "Aktif",
    slhs: "punya",
  },
];
